version: "3.9"
services:
  network-science-with-python:
    image: network-science-with-python
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      # jovyan でないとダメ
      - .:/home/jovyan/workdir
    command: start-notebook.sh --NotebookApp.token=''
